/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: '#b7c4ff',
        'on-primary': '#002682',
        'primary-container': '#6a89ff',
        'on-primary-container': '#002073',
        'inverse-primary': '#2a52d2',
        secondary: '#b8c4fe',
        'on-secondary': '#202d5d',
        'secondary-container': '#3a4678',
        'on-secondary-container': '#aab6ef',
        tertiary: '#ffb784',
        'on-tertiary ': '#4f2500',
        'tertiary-container': '#dc7518',
        'on-tertiary-container': '#451f00',
        background: '#12131b',
        'on-background': '#e3e1ed',
        surface: '#12131b',
        'surface-dim': '#12131b',
        'surface-bright': '#383941',
        'surface-container-lowest': '#0d0e15',
        'surface-container-low': '#1a1b23',
        'surface-container': '#1e1f27',
        'surface-container-high': '#292932',
        'surface-container-highest': '#33343d',
        'on-surface': '#e3e1ed',
        'on-surface-variant': '#c4c5d7',
        'inverse-surface': '#e3e1ed',
        'inverse-on-surface': '#2f3038',
        outline: '#8e90a0',
        'outline-variant': '#444654',
        'surface-tint': '#b7c4ff',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1.0rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        'sidebar-width': '280px',
        'playback-height': '88px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
      },
      scale: {
        '103': '1.03',
        '108': '1.08',
        '115': '1.15',
      },
    }
  },
  plugins: [],
}
